Added Japanese translation.
VoLuong/Begin-Latex-in-minutes pull request #50
Opened 2019-02-23 12:11 UTC by kzt206

I translated to Japanese.
This project is very useful for LaTex beginners.

I am started git and github recently.
I'm not sure to pull request.

2019-02-23 21:05 UTC, i-ky requested changes
I can't verify your Japanese text. Please Do the changes to the header and add links to your translation from other pages.

2019-02-23 21:05 UTC, i-ky commented on Translation:Japanese.md
> +English ·
This should link to English version:
```suggestion
[English](./readme.md) ·
```

2019-02-23 21:05 UTC, i-ky commented on Translation:Japanese.md
> +[日本語](.Translation:Japanese.md)
Add such link to your translation in other translations. But here remove the link:
```suggestion
日本語
```
Language without a link shows the reader which translation he/she is viewing. Have a look at other translations and do the same way.

2019-02-23 21:05 UTC, i-ky commented on Translation:Japanese.md
> +**初めに:** *この文書に書いていることは、私が大学での経験や目を通したいくつかの資料に基づくものです。私は、プロフェッショナルな仕事をしているわけでも、専門家でもなく、大いなる情熱を持つ学生です。問題セクションでは、誰でも議論に参加することを歓迎しますし、修正や加えるべきことがあれば、プルリクエストをすることができます。 もし、私のプロジェクトに価値があると思えば、ぜひ寄付[donatio
You can translate text in square brackets (`[donation]`) as well.

2019-02-24 11:57 UTC, i-ky commented
Good job! Please add a link from `readme.md` and `Translation:*.md` files to your translation. See bc6e56ac398c47af34efc0ebd12d10ce79b23e90 as an example.

2019-03-03 17:38 UTC, luong-komorebi commented
Awesome work, guys. I did send this to some of my friends who can read Japanese and they all commented LGTM <3

2019-03-03 17:38 UTC, luong-komorebi commented
Thank you so much for your work @kzt206 and your reviews @i-ky

2019-03-03 17:38 UTC, merged

2019-03-03 17:41 UTC, luong-komorebi commented on Translation:Japanese.md
> +**どうとでも勝手にしやがれクソッタレ・公衆利用許諾(契約)書**
Oh boy, I am so curious how WTFPL is translated to Japanese.